# Generated by Django 5.2.5 on 2025-09-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitflow', '0002_billuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='location',
            field=models.CharField(default='Varna, Bulgaria', max_length=50),
        ),
    ]
