# Generated by Django 5.2.5 on 2025-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitflow', '0003_bill_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
