# Generated by Django 5.2.5 on 2025-09-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitflow', '0004_alter_bill_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
